// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd7eUcGnyCebHSWzXgTf800rdg1_2jESo',
    appId: '1:398673468176:web:e585cc35ebd3a338a26395',
    messagingSenderId: '398673468176',
    projectId: 'sparepart-app-8df68',
    authDomain: 'sparepart-app-8df68.firebaseapp.com',
    storageBucket: 'sparepart-app-8df68.firebasestorage.app',
    measurementId: 'G-XMRM0DR5SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-msso0NOG19QdVe3jQ5hhsIu2d2vqGU',
    appId: '1:398673468176:android:e24a7d2cac31af00a26395',
    messagingSenderId: '398673468176',
    projectId: 'sparepart-app-8df68',
    storageBucket: 'sparepart-app-8df68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRSvHAC9pbLqg8CZbBEFUL18zKJk5bkFk',
    appId: '1:398673468176:ios:481723ccbffa609ca26395',
    messagingSenderId: '398673468176',
    projectId: 'sparepart-app-8df68',
    storageBucket: 'sparepart-app-8df68.firebasestorage.app',
    iosBundleId: 'com.example.spareartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRSvHAC9pbLqg8CZbBEFUL18zKJk5bkFk',
    appId: '1:398673468176:ios:481723ccbffa609ca26395',
    messagingSenderId: '398673468176',
    projectId: 'sparepart-app-8df68',
    storageBucket: 'sparepart-app-8df68.firebasestorage.app',
    iosBundleId: 'com.example.spareartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd7eUcGnyCebHSWzXgTf800rdg1_2jESo',
    appId: '1:398673468176:web:4fbad234df2b35c5a26395',
    messagingSenderId: '398673468176',
    projectId: 'sparepart-app-8df68',
    authDomain: 'sparepart-app-8df68.firebaseapp.com',
    storageBucket: 'sparepart-app-8df68.firebasestorage.app',
    measurementId: 'G-WY3JTN1HC2',
  );
}
